# Erweiterte Dokumentation: https://www.appveyor.com/docs/appveyor-yml/

# Version festlegen
version: 1.0.{build}

clone_folder: c:\projects\validationframework

skip_branch_with_pr: false

# VM-Template für Visual Studio 2017
image: Visual Studio 2017

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

platform: Any CPU
configuration: Release

matrix:
  fast_finish: true

environment:
  SONARQUBE_TOKEN:
    secure: Z4637knUKkjAjauYzNAXyFQkph2OKVE9AqGNBkvjrN6CCbjruk1k9acqL1KPd4Kq

before_build:
  - choco install "msbuild-sonarqube-runner" -y
  - dotnet restore c:\projects\validationframework\src\ValidationFramework.sln

build_script:
  - ps: MSBuild.SonarQube.Runner.exe begin /k:"ValidationFramework" /d:"sonar.host.url=https://sonarcloud.io" /d:"sonar.login=$($env:SONARQUBE_TOKEN)" /d:"sonar.exclusions=**/AssemblyInfo.cs" /d:"sonar.dotnet.visualstudio.testProjectPattern=*.Test" /v:"$($env:appveyor_build_version)"
  - dotnet build c:\projects\validationframework\src\ValidationFramework.sln -c Release
  - ps: MSBuild.SonarQube.Runner.exe end /d:"sonar.login=$($env:SONARQUBE_TOKEN)"

test_script:
  - dotnet test c:\projects\validationframework\src\ValidationFramework.Tests\ValidationFramework.Tests.csproj -c Release